# Generated by Django 6.0.3 on 2026-03-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_booking_check_in_booking_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('Sin', 'Single'), ('Dou', 'Double'), ('Suite', 'Suite'), ('Deluxe', 'Deluxe'), ('Family', 'Family')], max_length=20),
        ),
    ]
