# Generated by Django 6.0.3 on 2026-03-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('Suite', 'Suite'), ('Deluxe', 'Deluxe'), ('Family', 'Family')], max_length=20),
        ),
    ]
