# Generated by Django 6.0.3 on 2026-03-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_room_price_per_night_room_tag1_room_tag2_room_tag3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('single', 'Single'), ('dual', 'Dual'), ('suite', 'Suite'), ('deluxe', 'Deluxe'), ('family', 'Family')], max_length=20),
        ),
    ]
