# Generated by Django 6.0.3 on 2026-03-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='room_images/'),
        ),
    ]
